---
name: ((deployment))

releases:
  - name: vantablackbox
    version: latest

stemcells:
- alias: stemcell
  os: ((stemcell-os))
  version: latest

instance_groups:
- name: garden
  ...
- name: blackbox
  instances: 1
  vm_type: ((vm))
  networks:
  - name: ((network))
  azs: [((az))]
  stemcell: stemcell
  jobs:
  - name: blackbox
    release: vantablackbox
    properties:
      blackbox:
        expvar:
          datadog:
            api_key: "THE_KEY"
          interval_in_seconds: 10
          sources:
            goroutine:
              url: "http://10.244.16.6:17013/debug/pprof/goroutine"
              tags:
              - "garden-linux:goroutine"

                #            - `{ "goroutine" => { "url" => "http://10.244.16.6:17013/debug/pprof/goroutine", "tags"=> ["garden-linux:goroutine"] } }`

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 1000-240000
  update_watch_time: 1000-240000
